// Mapping of common IANA timezones to Country Names
export const zoneToCountry: Record<string, string> = {
    // Africa
    'Africa/Cairo': 'Egypt',
    'Africa/Johannesburg': 'South Africa',
    'Africa/Lagos': 'Nigeria',
    'Africa/Nairobi': 'Kenya',
    'Africa/Accra': 'Ghana',
    'Africa/Casablanca': 'Morocco',
    'Africa/Addis_Ababa': 'Ethiopia',
    'Africa/Abidjan': 'Ivory Coast',
    'Africa/Algiers': 'Algeria',
    'Africa/Dakar': 'Senegal',
    'Africa/Dar_es_Salaam': 'Tanzania',
    'Africa/Kinshasa': 'Congo (DRC)',
    'Africa/Lubumbashi': 'Congo (DRC)',
    'Africa/Khartoum': 'Sudan',
    'Africa/Luanda': 'Angola',
    'Africa/Maputo': 'Mozambique',
    'Africa/Tripoli': 'Libya',
    'Africa/Tunis': 'Tunisia',
    'Africa/Windhoek': 'Namibia',
    'Africa/Asmera': 'Eritrea',
    'Africa/Bamako': 'Mali',
    'Africa/Bangui': 'Central African Republic',
    'Africa/Banjul': 'Gambia',
    'Africa/Bissau': 'Guinea-Bissau',
    'Africa/Blantyre': 'Malawi',
    'Africa/Brazzaville': 'Congo',
    'Africa/Bujumbura': 'Burundi',
    'Africa/Ceuta': 'Spain',
    'Africa/Conakry': 'Guinea',
    'Africa/Djibouti': 'Djibouti',
    'Africa/Douala': 'Cameroon',
    'Africa/El_Aaiun': 'Western Sahara',
    'Africa/Freetown': 'Sierra Leone',
    'Africa/Gaborone': 'Botswana',
    'Africa/Harare': 'Zimbabwe',
    'Africa/Juba': 'South Sudan',
    'Africa/Kampala': 'Uganda',
    'Africa/Kigali': 'Rwanda',
    'Africa/Libreville': 'Gabon',
    'Africa/Lome': 'Togo',
    'Africa/Lusaka': 'Zambia',
    'Africa/Malabo': 'Equatorial Guinea',
    'Africa/Maseru': 'Lesotho',
    'Africa/Mbabane': 'Eswatini',
    'Africa/Mogadishu': 'Somalia',
    'Africa/Monrovia': 'Liberia',
    'Africa/Ndjamena': 'Chad',
    'Africa/Niamey': 'Niger',
    'Africa/Nouakchott': 'Mauritania',
    'Africa/Ouagadougou': 'Burkina Faso',
    'Africa/Porto-Novo': 'Benin',
    'Africa/Sao_Tome': 'Sao Tome and Principe',

    // Americas
    'America/New_York': 'United States',
    'America/Chicago': 'United States',
    'America/Denver': 'United States',
    'America/Los_Angeles': 'United States',
    'America/Phoenix': 'United States',
    'America/Anchorage': 'United States',
    'America/Detroit': 'United States',
    'America/Indianapolis': 'United States',
    'America/Louisville': 'United States',
    'America/Boise': 'United States',
    'America/Juneau': 'United States',
    'America/Sitka': 'United States',
    'America/Yakutat': 'United States',
    'America/Nome': 'United States',
    'America/Adak': 'United States',
    'America/Metlakatla': 'United States',
    'America/Indiana/Knox': 'United States',
    'America/Indiana/Marengo': 'United States',
    'America/Indiana/Petersburg': 'United States',
    'America/Indiana/Tell_City': 'United States',
    'America/Indiana/Vevay': 'United States',
    'America/Indiana/Vincennes': 'United States',
    'America/Indiana/Winamac': 'United States',
    'America/Kentucky/Monticello': 'United States',
    'America/Menominee': 'United States',
    'America/North_Dakota/Beulah': 'United States',
    'America/North_Dakota/Center': 'United States',
    'America/North_Dakota/New_Salem': 'United States',
    'America/Toronto': 'Canada',
    'America/Vancouver': 'Canada',
    'America/Edmonton': 'Canada',
    'America/Winnipeg': 'Canada',
    'America/Halifax': 'Canada',
    'America/St_Johns': 'Canada',
    'America/Moncton': 'Canada',
    'America/Regina': 'Canada',
    'America/Whitehorse': 'Canada',
    'America/Dawson': 'Canada',
    'America/Dawson_Creek': 'Canada',
    'America/Fort_Nelson': 'Canada',
    'America/Inuvik': 'Canada',
    'America/Iqaluit': 'Canada',
    'America/Rankin_Inlet': 'Canada',
    'America/Resolute': 'Canada',
    'America/Swift_Current': 'Canada',
    'America/Cambridge_Bay': 'Canada',
    'America/Coral_Harbour': 'Canada',
    'America/Blanc-Sablon': 'Canada',
    'America/Glace_Bay': 'Canada',
    'America/Goose_Bay': 'Canada',
    'America/Creston': 'Canada',
    'America/Mexico_City': 'Mexico',
    'America/Cancun': 'Mexico',
    'America/Merida': 'Mexico',
    'America/Monterrey': 'Mexico',
    'America/Matamoros': 'Mexico',
    'America/Mazatlan': 'Mexico',
    'America/Chihuahua': 'Mexico',
    'America/Tijuana': 'Mexico',
    'America/Hermosillo': 'Mexico',
    'America/Ojinaga': 'Mexico',
    'America/Bahia_Banderas': 'Mexico',
    'America/Sao_Paulo': 'Brazil',
    'America/Rio_Branco': 'Brazil',
    'America/Porto_Velho': 'Brazil',
    'America/Boa_Vista': 'Brazil',
    'America/Manaus': 'Brazil',
    'America/Cuiaba': 'Brazil',
    'America/Campo_Grande': 'Brazil',
    'America/Bahia': 'Brazil',
    'America/Belem': 'Brazil',
    'America/Fortaleza': 'Brazil',
    'America/Recife': 'Brazil',
    'America/Maceio': 'Brazil',
    'America/Santarem': 'Brazil',
    'America/Eirunepe': 'Brazil',
    'America/Noronha': 'Brazil',
    'America/Araguaina': 'Brazil',
    'America/Argentina/Buenos_Aires': 'Argentina',
    'America/Argentina/Cordoba': 'Argentina',
    'America/Argentina/Salta': 'Argentina',
    'America/Argentina/Jujuy': 'Argentina',
    'America/Argentina/Tucuman': 'Argentina',
    'America/Argentina/Catamarca': 'Argentina',
    'America/Argentina/La_Rioja': 'Argentina',
    'America/Argentina/San_Juan': 'Argentina',
    'America/Argentina/Mendoza': 'Argentina',
    'America/Argentina/San_Luis': 'Argentina',
    'America/Argentina/Rio_Gallegos': 'Argentina',
    'America/Argentina/Ushuaia': 'Argentina',
    'America/Bogota': 'Colombia',
    'America/Lima': 'Peru',
    'America/Santiago': 'Chile',
    'America/Punta_Arenas': 'Chile',
    'America/Coyhaique': 'Chile',
    'America/Caracas': 'Venezuela',
    'America/La_Paz': 'Bolivia',
    'America/Asuncion': 'Paraguay',
    'America/Montevideo': 'Uruguay',
    'America/Paramaribo': 'Suriname',
    'America/Cayenne': 'French Guiana',
    'America/Guyana': 'Guyana',
    'America/Guayaquil': 'Ecuador',
    'America/Panama': 'Panama',
    'America/Costa_Rica': 'Costa Rica',
    'America/Managua': 'Nicaragua',
    'America/Tegucigalpa': 'Honduras',
    'America/El_Salvador': 'El Salvador',
    'America/Guatemala': 'Guatemala',
    'America/Belize': 'Belize',
    'America/Havana': 'Cuba',
    'America/Jamaica': 'Jamaica',
    'America/Port-au-Prince': 'Haiti',
    'America/Santo_Domingo': 'Dominican Republic',
    'America/Puerto_Rico': 'Puerto Rico',
    'America/Port_of_Spain': 'Trinidad and Tobago',
    'America/Nassau': 'Bahamas',
    'America/Barbados': 'Barbados',
    'America/Curacao': 'Curaçao',
    'America/Aruba': 'Aruba',
    'America/Antigua': 'Antigua and Barbuda',
    'America/Anguilla': 'Anguilla',
    'America/Dominica': 'Dominica',
    'America/Grenada': 'Grenada',
    'America/Guadeloupe': 'Guadeloupe',
    'America/Martinique': 'Martinique',
    'America/Montserrat': 'Montserrat',
    'America/St_Kitts': 'Saint Kitts and Nevis',
    'America/St_Lucia': 'Saint Lucia',
    'America/St_Vincent': 'Saint Vincent',
    'America/Tortola': 'British Virgin Islands',
    'America/St_Thomas': 'U.S. Virgin Islands',
    'America/Grand_Turk': 'Turks and Caicos',
    'America/Cayman': 'Cayman Islands',
    'America/Kralendijk': 'Bonaire',
    'America/Lower_Princes': 'Sint Maarten',
    'America/Marigot': 'Saint Martin',
    'America/St_Barthelemy': 'Saint Barthélemy',
    'America/Miquelon': 'Saint Pierre and Miquelon',
    'America/Godthab': 'Greenland',
    'America/Danmarkshavn': 'Greenland',
    'America/Scoresbysund': 'Greenland',
    'America/Thule': 'Greenland',

    // Asia
    'Asia/Tokyo': 'Japan',
    'Asia/Shanghai': 'China',
    'Asia/Urumqi': 'China',
    'Asia/Hong_Kong': 'Hong Kong',
    'Asia/Macau': 'Macau',
    'Asia/Singapore': 'Singapore',
    'Asia/Seoul': 'South Korea',
    'Asia/Pyongyang': 'North Korea',
    'Asia/Bangkok': 'Thailand',
    'Asia/Dubai': 'United Arab Emirates',
    'Asia/Kolkata': 'India',
    'Asia/Jakarta': 'Indonesia',
    'Asia/Makassar': 'Indonesia',
    'Asia/Pontianak': 'Indonesia',
    'Asia/Jayapura': 'Indonesia',
    'Asia/Ho_Chi_Minh': 'Vietnam',
    'Asia/Taipei': 'Taiwan',
    'Asia/Manila': 'Philippines',
    'Asia/Kuala_Lumpur': 'Malaysia',
    'Asia/Kuching': 'Malaysia',
    'Asia/Riyadh': 'Saudi Arabia',
    'Asia/Tel_Aviv': 'Israel',
    'Asia/Jerusalem': 'Israel',
    'Asia/Baghdad': 'Iraq',
    'Asia/Tehran': 'Iran',
    'Asia/Karachi': 'Pakistan',
    'Asia/Kabul': 'Afghanistan',
    'Asia/Tashkent': 'Uzbekistan',
    'Asia/Samarkand': 'Uzbekistan',
    'Asia/Almaty': 'Kazakhstan',
    'Asia/Aqtau': 'Kazakhstan',
    'Asia/Aqtobe': 'Kazakhstan',
    'Asia/Atyrau': 'Kazakhstan',
    'Asia/Oral': 'Kazakhstan',
    'Asia/Qostanay': 'Kazakhstan',
    'Asia/Qyzylorda': 'Kazakhstan',
    'Asia/Bishkek': 'Kyrgyzstan',
    'Asia/Dushanbe': 'Tajikistan',
    'Asia/Ashgabat': 'Turkmenistan',
    'Asia/Baku': 'Azerbaijan',
    'Asia/Yerevan': 'Armenia',
    'Asia/Tbilisi': 'Georgia',
    'Asia/Kathmandu': 'Nepal',
    'Asia/Katmandu': 'Nepal',
    'Asia/Thimphu': 'Bhutan',
    'Asia/Dhaka': 'Bangladesh',
    'Asia/Colombo': 'Sri Lanka',
    'Asia/Yangon': 'Myanmar',
    'Asia/Rangoon': 'Myanmar',
    'Asia/Vientiane': 'Laos',
    'Asia/Phnom_Penh': 'Cambodia',
    'Asia/Brunei': 'Brunei',
    'Asia/Dili': 'Timor-Leste',
    'Asia/Ulaanbaatar': 'Mongolia',
    'Asia/Hovd': 'Mongolia',
    'Asia/Choibalsan': 'Mongolia',
    'Asia/Beirut': 'Lebanon',
    'Asia/Amman': 'Jordan',
    'Asia/Damascus': 'Syria',
    'Asia/Gaza': 'Palestine',
    'Asia/Hebron': 'Palestine',
    'Asia/Kuwait': 'Kuwait',
    'Asia/Bahrain': 'Bahrain',
    'Asia/Qatar': 'Qatar',
    'Asia/Aden': 'Yemen',
    'Asia/Muscat': 'Oman',
    'Asia/Nicosia': 'Cyprus',
    'Asia/Famagusta': 'Cyprus',
    'Asia/Novosibirsk': 'Russia',
    'Asia/Krasnoyarsk': 'Russia',
    'Asia/Irkutsk': 'Russia',
    'Asia/Yakutsk': 'Russia',
    'Asia/Vladivostok': 'Russia',
    'Asia/Sakhalin': 'Russia',
    'Asia/Magadan': 'Russia',
    'Asia/Kamchatka': 'Russia',
    'Asia/Anadyr': 'Russia',
    'Asia/Yekaterinburg': 'Russia',
    'Asia/Omsk': 'Russia',
    'Asia/Barnaul': 'Russia',
    'Asia/Tomsk': 'Russia',
    'Asia/Novokuznetsk': 'Russia',
    'Asia/Khandyga': 'Russia',
    'Asia/Ust-Nera': 'Russia',
    'Asia/Chita': 'Russia',
    'Asia/Srednekolymsk': 'Russia',

    // Europe
    'Europe/London': 'United Kingdom',
    'Europe/Paris': 'France',
    'Europe/Berlin': 'Germany',
    'Europe/Busingen': 'Germany',
    'Europe/Rome': 'Italy',
    'Europe/Madrid': 'Spain',
    'Europe/Moscow': 'Russia',
    'Europe/Samara': 'Russia',
    'Europe/Volgograd': 'Russia',
    'Europe/Saratov': 'Russia',
    'Europe/Ulyanovsk': 'Russia',
    'Europe/Kirov': 'Russia',
    'Europe/Astrakhan': 'Russia',
    'Europe/Kaliningrad': 'Russia',
    'Europe/Istanbul': 'Turkey',
    'Europe/Amsterdam': 'Netherlands',
    'Europe/Brussels': 'Belgium',
    'Europe/Zurich': 'Switzerland',
    'Europe/Vienna': 'Austria',
    'Europe/Stockholm': 'Sweden',
    'Europe/Oslo': 'Norway',
    'Europe/Copenhagen': 'Denmark',
    'Europe/Helsinki': 'Finland',
    'Europe/Mariehamn': 'Aland Islands',
    'Europe/Warsaw': 'Poland',
    'Europe/Prague': 'Czech Republic',
    'Europe/Budapest': 'Hungary',
    'Europe/Athens': 'Greece',
    'Europe/Lisbon': 'Portugal',
    'Europe/Dublin': 'Ireland',
    'Europe/Kyiv': 'Ukraine',
    'Europe/Kiev': 'Ukraine',
    'Europe/Simferopol': 'Ukraine',
    'Europe/Bucharest': 'Romania',
    'Europe/Belgrade': 'Serbia',
    'Europe/Sofia': 'Bulgaria',
    'Europe/Tirane': 'Albania',
    'Europe/Zagreb': 'Croatia',
    'Europe/Sarajevo': 'Bosnia',
    'Europe/Skopje': 'North Macedonia',
    'Europe/Ljubljana': 'Slovenia',
    'Europe/Bratislava': 'Slovakia',
    'Europe/Chisinau': 'Moldova',
    'Europe/Minsk': 'Belarus',
    'Europe/Riga': 'Latvia',
    'Europe/Vilnius': 'Lithuania',
    'Europe/Tallinn': 'Estonia',
    'Europe/Luxembourg': 'Luxembourg',
    'Europe/Monaco': 'Monaco',
    'Europe/Malta': 'Malta',
    'Europe/San_Marino': 'San Marino',
    'Europe/Vatican': 'Vatican City',
    'Europe/Vaduz': 'Liechtenstein',
    'Europe/Andorra': 'Andorra',
    'Europe/Gibraltar': 'Gibraltar',
    'Europe/Isle_of_Man': 'Isle of Man',
    'Europe/Jersey': 'Jersey',
    'Europe/Guernsey': 'Guernsey',
    'Europe/Podgorica': 'Montenegro',

    // Oceania
    'Australia/Sydney': 'Australia',
    'Australia/Melbourne': 'Australia',
    'Australia/Brisbane': 'Australia',
    'Australia/Perth': 'Australia',
    'Australia/Adelaide': 'Australia',
    'Australia/Hobart': 'Australia',
    'Australia/Darwin': 'Australia',
    'Australia/Broken_Hill': 'Australia',
    'Australia/Lindeman': 'Australia',
    'Australia/Eucla': 'Australia',
    'Australia/Lord_Howe': 'Australia',
    'Pacific/Auckland': 'New Zealand',
    'Pacific/Chatham': 'New Zealand',
    'Pacific/Fiji': 'Fiji',
    'Pacific/Port_Moresby': 'Papua New Guinea',
    'Pacific/Bougainville': 'Papua New Guinea',
    'Pacific/Noumea': 'New Caledonia',
    'Pacific/Guam': 'Guam',
    'Pacific/Saipan': 'Northern Mariana Islands',
    'Pacific/Tahiti': 'French Polynesia',
    'Pacific/Marquesas': 'French Polynesia',
    'Pacific/Gambier': 'French Polynesia',
    'Pacific/Honolulu': 'United States',
    'Pacific/Pago_Pago': 'American Samoa',
    'Pacific/Midway': 'United States',
    'Pacific/Wake': 'United States',
    'Pacific/Tongatapu': 'Tonga',
    'Pacific/Apia': 'Samoa',
    'Pacific/Guadalcanal': 'Solomon Islands',
    'Pacific/Efate': 'Vanuatu',
    'Pacific/Palau': 'Palau',
    'Pacific/Pohnpei': 'Micronesia',
    'Pacific/Ponape': 'Micronesia',
    'Pacific/Kosrae': 'Micronesia',
    'Pacific/Chuuk': 'Micronesia',
    'Pacific/Truk': 'Micronesia',
    'Pacific/Majuro': 'Marshall Islands',
    'Pacific/Kwajalein': 'Marshall Islands',
    'Pacific/Tarawa': 'Kiribati',
    'Pacific/Enderbury': 'Kiribati',
    'Pacific/Kiritimati': 'Kiribati',
    'Pacific/Nauru': 'Nauru',
    'Pacific/Funafuti': 'Tuvalu',
    'Pacific/Wallis': 'Wallis and Futuna',
    'Pacific/Niue': 'Niue',
    'Pacific/Rarotonga': 'Cook Islands',
    'Pacific/Norfolk': 'Norfolk Island',
    'Pacific/Pitcairn': 'Pitcairn Islands',
    'Pacific/Easter': 'Chile',
    'Pacific/Galapagos': 'Ecuador',
    'Pacific/Fakaofo': 'Tokelau',

    // Atlantic
    'Atlantic/Azores': 'Portugal',
    'Atlantic/Madeira': 'Portugal',
    'Atlantic/Canary': 'Spain',
    'Atlantic/Bermuda': 'Bermuda',
    'Atlantic/Reykjavik': 'Iceland',
    'Atlantic/Cape_Verde': 'Cape Verde',
    'Atlantic/South_Georgia': 'South Georgia',
    'Atlantic/Stanley': 'Falkland Islands',
    'Atlantic/St_Helena': 'St. Helena',
    'Atlantic/Faeroe': 'Faroe Islands',

    // Indian
    'Indian/Mauritius': 'Mauritius',
    'Indian/Reunion': 'Réunion',
    'Indian/Chagos': 'British Indian Ocean Territory',
    'Indian/Maldives': 'Maldives',
    'Indian/Mahe': 'Seychelles',
    'Indian/Antananarivo': 'Madagascar',
    'Indian/Comoro': 'Comoros',
    'Indian/Mayotte': 'Mayotte',
    'Indian/Christmas': 'Christmas Island',
    'Indian/Cocos': 'Cocos (Keeling) Islands',
    'Indian/Kerguelen': 'French Southern Territories',

    // Antarctica
    'Antarctica/McMurdo': 'Antarctica',
    'Antarctica/Palmer': 'Antarctica',
    'Antarctica/Rothera': 'Antarctica',
    'Antarctica/Troll': 'Antarctica',
    'Antarctica/Vostok': 'Antarctica',
    'Antarctica/Davis': 'Antarctica',
    'Antarctica/Mawson': 'Antarctica',
    'Antarctica/Casey': 'Antarctica',
    'Antarctica/DumontDUrville': 'Antarctica',
    'Antarctica/Syowa': 'Antarctica',
    'Antarctica/Macquarie': 'Antarctica',

    // Arctic
    'Arctic/Longyearbyen': 'Svalbard',

    // Fallback/Default
    'UTC': 'Universal Time',

};

export const getCountryName = (zone: string): string => {
    if (zoneToCountry[zone]) {
        return zoneToCountry[zone];
    }
    // Fallback: try to extract from zone name
    if (zone.includes('/')) {
        const parts = zone.split('/');
        // e.g. "Europe/Andorra" -> "Andorra"
        return parts[parts.length - 1].replace(/_/g, ' ');
    }
    return zone;
};
